name: "Linux Hosts File Editor"
file_path: "/etc/hosts"
run_as_sudo: true

window:
  width: 600
  height: 400
  title: "Hosts File Manager"

fields:
  - name: "ip_address"
    type: "textbox"
    label: "IP Address"
    position:
      x: 10
      y: 50
      width: 150
      height: 30
    on_change: |
      #!/bin/bash
      IP=$(get_control "ip_address")
      if [[ ! $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        set_control "status" "Invalid IP format"
      else
        set_control "status" "IP valid"
      fi
      
  - name: "hostname"
    type: "textbox"
    label: "Hostname"
    position:
      x: 180
      y: 50
      width: 200
      height: 30
      
  - name: "add_button"
    type: "button"
    text: "Add Entry"
    position:
      x: 400
      y: 50
      width: 120
      height: 30
    on_click: |
      #!/bin/bash
      IP=$(get_control "ip_address")
      HOST=$(get_control "hostname")
      echo "$IP    $HOST" >> /etc/hosts
      set_control "status" "Added: $IP -> $HOST"
      set_control "ip_address" ""
      set_control "hostname" ""
      
  - name: "status"
    type: "label"
    position:
      x: 10
      y: 100
      width: 500
      height: 30
